import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/providers/auth-provider";

const robotoSans = Roboto({
    variable: "--font-roboto",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const robotoMono = Roboto_Mono({
    variable: "--font-roboto-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// TODO: Look at metadata
// TODO: Style delete/edit button
// TODO: Add task list update view
// TODO: Add task list delete button

export default async function RootLayout({children, params}: LayoutProps<"/[lang]">) {
    const {lang} = await params;
    return (
        <html
            lang={lang}
            className={`${robotoSans.variable} ${robotoMono.variable} h-full antialiased`}
        >
        <body className="min-h-full flex flex-col">
        <AuthProvider>
            {children}
        </AuthProvider>
        </body>
        </html>
    );
}
